name: "Request review of a FPWD"
description: Use this if you are approaching or have just passed FPWD.
title: Document_name    2023-mm-dd
labels: [ "REVIEW REQUESTED", FPWD, pending ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Note that the i18n WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://www.w3.org/International/review-request#selfreview.
        If you still want us to review your spec, please provide the information below.
        In the issue title above add the document name followed by the date of this request.
  - type: input
    id: spec-name
    attributes:
      label: Name of your specification
      description: Copy and paste title of your specification
      placeholder: Name of specification
    validations:
      required: true
  - type: input
    id: spec-url
    attributes:
      label: URL of your specification
      placeholder: https://www.w3.org/TR/...
    validations:
      required: true
  - type: checkboxes
    id: spec-i18n-section
    attributes:
      label: Does your specification include an Internationalization Considerations section?
      description: If your specification includes an [Internationalization Considerations section](https://www.w3.org/TR/international-specs/#I18N_Considerations), mark this checkbox.
      options:
        - label: My specification includes an Internationalization Considerations section
  - type: input
    id: date
    attributes:
      label: Do you need a reply by a particular date?
      description: If any date, type here
  - type: input
    id: self
    attributes:
      label: Please point to the results of your own self-review
      description: See https://w3c.github.io/i18n-drafts/techniques/shortchecklist.
      placeholder: Link to the desired location
  - type: input
    id: filing
    attributes:
      label: Where and how should the i18n WG raise issues?
      description: We prefer to use the issue list in your document's repo.
      placeholder: Link to the desired location
  - type: input
    id: explainer
    attributes:
      label: Pointer to any explainer for the spec
      placeholder: Add a URL.
  - type: textarea
    attributes:
      label: Other comments
